// Generated by build.py - edit there, not here.
// The service's generated Railway domain: routes to his app directly, no
// Host-header tricks (Cloudflare strips those - the old CNAME targets
// only answered to Host www.newsnownext.org and were unreachable here).
var RAILWAY = 'https://newsnownext-production.up.railway.app';
var CNBC_URL = "https://quote.cnbc.com/quote-html-webservice/restQuote/symbolType/symbol?symbols=.SPX|.IXIC|.DJI|.VIX|.FTSE|.GDAXI|.FCHI|.STOXX50E|US3M|US5Y|US10Y|US30Y|@GC.1|@SI.1|@CL.1|@NG.1&requestMethod=itv&noform=1&partnerId=2&fund=1&exthrs=1&output=json&events=1";

function num(v) {
  if (v === null || v === undefined) return null;
  var t = String(v).replace(/,/g, '').replace(/%/g, '').trim();
  if (t === '' || t === 'UNCH' || t === 'N/A' || t === '--') return 0;
  var n = parseFloat(t);
  return isNaN(n) ? null : n;
}

async function quotes(ctx) {
  var cache = caches.default;
  var key = new Request('https://quotes.internal/api/quotes');
  var hit = await cache.match(key);
  if (hit) return hit;
  var r = await fetch(CNBC_URL, {headers: {'User-Agent': 'Mozilla/5.0'}});
  if (!r.ok) return new Response('{}', {status: 502,
    headers: {'content-type': 'application/json'}});
  var raw = await r.json();
  var rows = ((raw.FormattedQuoteResult || {}).FormattedQuote) || [];
  var out = {};
  for (var i = 0; i < rows.length; i++) {
    var q = rows[i];
    var last = num(q.last), change = num(q.change);
    if (last === null || change === null) continue;
    var prev = last - change;
    out[q.symbol] = {price: last, change: change,
                     pct: prev ? change / prev * 100 : 0};
  }
  var res = new Response(JSON.stringify({t: Date.now(), q: out}), {
    headers: {'content-type': 'application/json',
              'cache-control': 'public, s-maxage=15, max-age=5'}});
  ctx.waitUntil(cache.put(key, res.clone()));
  return res;
}

async function railway(request, url) {
  var target = RAILWAY + url.pathname + url.search;
  try {
    return await fetch(target, {
      method: request.method, headers: request.headers,
      body: (request.method === 'GET' || request.method === 'HEAD')
        ? undefined : request.body,
      redirect: 'manual',
    });
  } catch (e) {
    return null;
  }
}

function fromRailway(res) {
  return res && res.status < 500 && !res.headers.get('x-railway-fallback');
}

// The daily brief, written from /brief-admin and stored in KV so the
// client never needs GitHub. The hourly build pulls it back out and
// bakes it into the page and the recap.
function briefJson(obj, status, cache) {
  return new Response(JSON.stringify(obj), {status: status || 200,
    headers: {'content-type': 'application/json',
              'cache-control': cache || 'no-store'}});
}

async function brief(request, env, url) {
  if (!env.BRIEFS) {
    return briefJson({error: 'storage not configured'}, 503);
  }
  if (request.method === 'GET') {
    var d = url.searchParams.get('date') || '';
    if (!/^\d{4}-\d{2}-\d{2}$/.test(d)) return briefJson({error: 'bad date'}, 400);
    var text = await env.BRIEFS.get('brief:' + d);
    return briefJson({date: d, text: text || ''}, 200, 'public, max-age=60');
  }
  if (request.method === 'POST') {
    if (!env.BRIEF_KEY) return briefJson({error: 'no key configured'}, 503);
    var b;
    try { b = await request.json(); } catch (e) { return briefJson({error: 'bad json'}, 400); }
    if (!/^\d{4}-\d{2}-\d{2}$/.test(b.date || '')) return briefJson({error: 'bad date'}, 400);
    if ((b.key || '') !== env.BRIEF_KEY) return briefJson({error: 'wrong passphrase'}, 401);
    await env.BRIEFS.put('brief:' + b.date, String(b.text || '').slice(0, 6000));
    return briefJson({ok: true, date: b.date});
  }
  return briefJson({error: 'method'}, 405);
}

export default {
  async fetch(request, env, ctx) {
    var url = new URL(request.url);
    if (url.pathname === '/api/quotes') return quotes(ctx);
    if (url.pathname === '/api/brief') return brief(request, env, url);
    if (url.pathname.startsWith('/api/')) {
      var r = await railway(request, url);
      return r || new Response('{"error":"backend unreachable"}', {
        status: 502, headers: {'content-type': 'application/json'}});
    }
    // The portfolio system's pages in his app: /stocks is the portfolio
    // itself, the rest are its login flow. All proxied; if the backend is
    // down, the static portfolio page explains instead of erroring.
    var SPA = ['/stocks', '/login', '/register', '/forgot-password',
               '/reset-password', '/portfolio'];
    var path = url.pathname.replace(/\/+$/, '') || '/';
    // His admin area (Manage Podcasts, messages) rides along too - it is
    // part of the same app, gated by his admin login.
    if (SPA.indexOf(path) !== -1 || path === '/admin' || path.startsWith('/admin/')) {
      if (path !== url.pathname) {
        return Response.redirect(url.origin + path + url.search, 301);
      }
      var p = await railway(request, url);
      if (fromRailway(p)) return p;
      return env.ASSETS.fetch(new Request(url.origin + '/portfolio/', request));
    }
    var res = await env.ASSETS.fetch(request);
    // The old app's hashed bundles (its /assets/index-*.js) are not in the
    // static build; let them fall through to the backend.
    if (res.status === 404 && url.pathname.startsWith('/assets/')) {
      var a = await railway(request, url);
      if (fromRailway(a)) return a;
    }
    return res;
  },
};